server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/eacdy/spring-cloud-study/     # 配置git仓库的地址
#          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username:                                             # git仓库的账号
#          password:                                             # git仓库的密码
          #in Windows you need an extra "/" in the file URL if it is absolute with a drive prefix, e.g. file:///${user.home}/config-repo.
          uri: file://config-repo/

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/